name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - tag: xundaoxd/base:latest
            docker: base/Dockerfile
          - tag: xundaoxd/base-cuda:latest
            docker: base/Dockerfile.cuda
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-base
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.docker }}
      - uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.docker }}
          tags: ${{ matrix.tag }}
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context:
          - doxygen
          - you-get
          - go
          - vlc
          - gimp
          - onedrive
          - cuda-cmake
          - obsidian
          - octave
          - genymotion
          - blender
    needs: [base]
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.context }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.context }}
      - uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.context }}/Dockerfile
          tags: xundaoxd/${{ matrix.context }}:latest
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
