name: ci

on:
  push:
    branches:
      - master
      - force_run

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context:
          - ml
    steps:
      - name: Sync ml
        uses: onichandame/docker-registry-sync-action@master
        with:
          source_repository: docker.io/xundaoxd/ml:latest
          target_repository: registry.cn-hangzhou.aliyuncs.com/xundaoxd/ml:latest
          target_username: ${{ secrets.ALIYUN_USERNAME }}
          target_password: ${{ secrets.ALIYUN_TOKEN }}

