name: ci

on:
  push:
    branches:
      - master
      - force_run

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          file: dockerfiles/base/Dockerfile
          tags: xundaoxd/base:latest
          push: true

  ml:
    runs-on: ubuntu-latest
    needs: base
    steps:
      - run: |
          curl -L https://raw.githubusercontent.com/apache/flink/master/tools/azure-pipelines/free_disk_space.sh | bash
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          file: dockerfiles/ml/Dockerfile
          tags: xundaoxd/ml:latest
          push: true

  obsidian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          file: dockerfiles/obsidian/Dockerfile
          tags: xundaoxd/obsidian:latest
          push: true

