name: ci

on:
  push:
    branches:
      - master
      - force_run

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context:
          - ml
    steps:
      - run: |
          curl -L https://raw.githubusercontent.com/apache/flink/master/tools/azure-pipelines/free_disk_space.sh | bash
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: gaoyincao140
          password: docker1234
      - uses: docker/build-push-action@v3
        with:
          context: .
          file: dockerfiles/${{ matrix.context }}/Dockerfile
          tags: registry.cn-hangzhou.aliyuncs.com/xundaoxd/ml:latest
          push: true

