name: ci

on:
  push:
    branches:
      - master

jobs:
  base:
    uses: xundaoxd/docker-apps/.github/workflows/action.yml@master
    with:
      dockerfile: dockerfiles/base/Dockerfile
      tag: xundaoxd/base:11.6.2-cudnn8-devel-ubuntu20.04-py3.8
      build-args: 'BASE_IMAGE=nvidia/cuda:11.6.2-cudnn8-devel-ubuntu20.04'
    secrets: inherit

  ml:
    needs: base
    uses: xundaoxd/docker-apps/.github/workflows/action.yml@master
    with:
      dockerfile: dockerfiles/ml/Dockerfile
      tag: xundaoxd/ml:latest
      build-args: 'BASE_IMAGE=xundaoxd/base:11.6.2-cudnn8-devel-ubuntu20.04-py3.8'
    secrets: inherit

  obsidian:
    uses: xundaoxd/docker-apps/.github/workflows/action.yml@master
    with:
      dockerfile: dockerfiles/obsidian/Dockerfile
      tag: xundaoxd/obsidian:latest
    secrets: inherit

