name: ci

on:
  push:
    branches:
      - master
      - dev
      - force_run

jobs:
  base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - tag: xundaoxd/base:latest
            docker: base/Dockerfile
          - tag: xundaoxd/base-cuda:latest
            docker: base/Dockerfile.cuda
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            dockerfiles/${{ matrix.docker }}
            dockerfiles/base/Dockerfile.common
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - run: |
          cat dockerfiles/base/Dockerfile.common >> dockerfiles/${{ matrix.docker }}
      - uses: docker/build-push-action@v2
        if: ${{ env.GIT_DIFF || github.ref == 'refs/heads/force_run' }}
        with:
          context: .
          file: dockerfiles/${{ matrix.docker }}
          tags: ${{ matrix.tag }}
          push: true

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context:
          - doxygen
          - you-get
          - go
          - vlc
          - gimp
          - onedrive
          - development
          - obsidian
          - octave
          - blender
    needs: [base]
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            dockerfiles/${{ matrix.context }}/Dockerfile
            dockerfiles/base/*
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/build-push-action@v2
        if: ${{ env.GIT_DIFF || github.ref == 'refs/heads/force_run' }}
        with:
          context: .
          file: dockerfiles/${{ matrix.context }}/Dockerfile
          tags: xundaoxd/${{ matrix.context }}:latest
          push: true
  
  build1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context:
          - ml
          - vscode
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            dockerfiles/${{ matrix.context }}/Dockerfile
            dockerfiles/base/*
            dockerfiles/development/Dockerfile
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/build-push-action@v2
        if: ${{ env.GIT_DIFF || github.ref == 'refs/heads/force_run' }}
        with:
          context: .
          file: dockerfiles/${{ matrix.context }}/Dockerfile
          tags: xundaoxd/${{ matrix.context }}:latest
          push: true
