on:
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string
      tag:
        required: true
        type: string
      platforms:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -L https://raw.githubusercontent.com/apache/flink/master/tools/azure-pipelines/free_disk_space.sh | bash
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          tags: ${{ inputs.tag }}
          platforms: ${{ inputs.platforms }}
          push: true

