name: ci

on:
  push:
    branches:
      - master
      - force_run

jobs:
  base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - tag: xundaoxd/base:latest
            docker: base/Dockerfile
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        if: ${{ github.ref != 'refs/heads/force_run' }}
        with:
          PATTERNS: |
            dockerfiles/${{ matrix.docker }}
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/build-push-action@v2
        if: ${{ env.GIT_DIFF || github.ref == 'refs/heads/force_run' }}
        with:
          context: .
          file: dockerfiles/${{ matrix.docker }}
          tags: ${{ matrix.tag }}
          push: true
  
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context:
          - ml
    needs: [base]
    steps:
      - run: |
          curl -L https://raw.githubusercontent.com/apache/flink/master/tools/azure-pipelines/free_disk_space.sh | bash
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        if: ${{ github.ref != 'refs/heads/force_run' }}
        with:
          PATTERNS: |
            dockerfiles/${{ matrix.context }}/Dockerfile
            dockerfiles/base/*
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/build-push-action@v2
        if: ${{ env.GIT_DIFF || github.ref == 'refs/heads/force_run' }}
        with:
          context: .
          file: dockerfiles/${{ matrix.context }}/Dockerfile
          tags: xundaoxd/${{ matrix.context }}:latest
          push: true
