name: ci

on:
  push:
    branches:
      - master

jobs:
  ml:
    uses: xundaoxd/docker-apps/.github/workflows/action.yml@master
    with:
      dockerfile: dockerfiles/ml/Dockerfile
      tag: xundaoxd/ml:latest
    secrets: inherit

  obsidian:
    uses: xundaoxd/docker-apps/.github/workflows/action.yml@master
    with:
      dockerfile: dockerfiles/x11gui/Dockerfile
      tag: xundaoxd/x11gui:latest
    secrets: inherit

