name: ci

on:
  push:
    branches:
      - master

jobs:
  ml:
    uses: ./.github/workflows/build.yml
    with:
      dockerfile: dockerfiles/ml/Dockerfile
      tag: ghcr.io/xundaoxd/ml:latest
      platforms: linux/amd64

