name: ci

on:
  push:
    branches:
      - master

jobs:
  ml:
    uses: ./.github/workflows/build.yml
    with:
      dockerfile: dockerfiles/ml/Dockerfile
      tag: ghcr.io/xundaoxd/ml:latest
      platforms: linux/amd64
    secrets: inherit

  sysroot:
    uses: ./.github/workflows/build.yml
    with:
      dockerfile: dockerfiles/ml/Dockerfile.sysroot
      tag: ghcr.io/xundaoxd/ml:sysroot-latest
      platforms: linux/arm64
    secrets: inherit

  ml-cross:
    uses: ./.github/workflows/build.yml
    needs: [ml, sysroot]
    with:
      dockerfile: dockerfiles/ml/Dockerfile.cross
      tag: ghcr.io/xundaoxd/ml:cross-latest
      platforms: linux/amd64
    secrets: inherit
